# -*- coding: utf-8 -*-
"""trabalho2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ifNqqLrgTpUpbNkS0p3GNXIf_j8xiJWy
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

file_path = "1.xls"
df = pd.read_excel(file_path)

bill_amt_list = ['BILL_AMT1', 'BILL_AMT2', 'BILL_AMT3', 'BILL_AMT4', 'BILL_AMT5', 'BILL_AMT6']

pay_amt_list = ['PAY_AMT1', 'PAY_AMT2', 'PAY_AMT3', 'PAY_AMT4', 'PAY_AMT5', 'PAY_AMT6']

"""exercicio 1 criando as listas"""

df[bill_amt_list].describe()

"""valores minimos com negativos bem grandes vão atrapalhar as medias"""

df[bill_amt_list].hist(bins=20, figsize=(15, 10))
plt.tight_layout()
plt.show()

"""não me tem nenhuma informação relevante"""

df[pay_amt_list].describe()

"""me parece que a maioria dos pagametos são valores relativamente pequenos"""

df[pay_amt_list].hist(bins=20, figsize=(15, 10), xrot=45)
plt.tight_layout()
plt.show()

"""os valores de 0 fazem outros ficarem quase "invisiveis" para qualquer analise (no grafico)"""

(df[pay_amt_list] == 0).sum()

"""confirma que o 0 é mais comum"""

df_log = df[pay_amt_list].apply(lambda x: np.log10(x[x > 0]))
df_log.hist(bins=20, figsize=(15, 10))
plt.tight_layout()
plt.show()

"""esses ultimos graficos ficaram bem mais proximos da distribuição padrão"""